-- =====================================================
-- 02-dimensoes-prontas.sql
-- Cria dim_tempo e dim_loja
-- =====================================================

DROP TABLE IF EXISTS dim_tempo CASCADE;
CREATE TABLE dim_tempo (
    sk_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_referencia DATE,
    ano INT,
    mes INT,
    dia INT,
    trimestre INT,
    dia_semana VARCHAR(20),
    mes_nome VARCHAR(20)
);

INSERT INTO dim_tempo (sk_tempo, data_referencia) VALUES (-1, NULL);

INSERT INTO dim_tempo (data_referencia, ano, mes, dia, trimestre, dia_semana, mes_nome)
SELECT 
    data_referencia::date,
    EXTRACT(YEAR FROM data_referencia)::INT,
    EXTRACT(MONTH FROM data_referencia)::INT,
    EXTRACT(DAY FROM data_referencia)::INT,
    EXTRACT(QUARTER FROM data_referencia)::INT,
    TO_CHAR(data_referencia, 'Day'),
    TO_CHAR(data_referencia, 'Month')
FROM generate_series('2023-09-01'::date, '2024-04-30'::date, '1 day'::interval) AS data_referencia;

DROP TABLE IF EXISTS dim_loja CASCADE;
CREATE TABLE dim_loja (
    sk_loja INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_loja VARCHAR(10),
    chave_loja VARCHAR(80),
    nome_loja VARCHAR(80),
    cidade VARCHAR(50),
    uf VARCHAR(2),
    mesorregiao VARCHAR(50),
    populacao_cidade INT,
    area_venda_m2 INT,
    porte VARCHAR(20),
    faixa_franquia VARCHAR(15),
    formato_loja VARCHAR(20)
);

INSERT INTO dim_loja (sk_loja, cod_loja, chave_loja, nome_loja)
VALUES (-1, '-1', 'NAO INFORMADO', 'Nao Informado');

INSERT INTO dim_loja (cod_loja, chave_loja, nome_loja, cidade, uf, mesorregiao, populacao_cidade, area_venda_m2, porte, faixa_franquia, formato_loja)
SELECT 
    "Cod Loja",
    UPPER(unaccent("Loja-Nome")),
    "Loja-Nome",
    "Cidade",
    "UF",
    "Mesorregiao",
    CAST(REPLACE("Populacao_Cidade", '.', '') AS INTEGER),
    CAST("Area_Venda_m2" AS INTEGER),
    CASE 
        WHEN CAST("Area_Venda_m2" AS INTEGER) < 200 THEN 'Pequena'
        WHEN CAST("Area_Venda_m2" AS INTEGER) < 400 THEN 'Media'
        ELSE 'Grande'
    END,
    "Faixa_Franquia",
    "Formato_Loja"
FROM stg_loja
WHERE "Cod Loja" IS NOT NULL AND "Cod Loja" != '';
