-- =====================================================
-- 03-dim_categoria.sql
-- Cria dim_categoria (MED antes de RA)
-- =====================================================

DROP TABLE IF EXISTS dim_categoria CASCADE;
CREATE TABLE dim_categoria (
    sk_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_origem VARCHAR(50),
    nome_categoria VARCHAR(30),
    grupo_categoria VARCHAR(20)
);

INSERT INTO dim_categoria (sk_categoria, categoria_origem, nome_categoria, grupo_categoria)
VALUES (-1, 'Nao Informado', 'Nao Informado', 'Nao Informado');

INSERT INTO dim_categoria (categoria_origem, nome_categoria, grupo_categoria)
SELECT DISTINCT 
    "CategoriaProduto",
    CASE 
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%MED%' THEN 'Medicamento'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%PETISC%' THEN 'Petisco'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%RA%' THEN 'Racao'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%HIG%' THEN 'Higiene'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%BRINQ%' THEN 'Brinquedo'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%ACESS%' THEN 'Acessorio'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%SERV%' THEN 'Servico'
        ELSE 'Nao Informado'
    END,
    CASE 
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%MED%' THEN 'Saude e Higiene'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%PETISC%' THEN 'Alimentacao'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%RA%' THEN 'Alimentacao'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%HIG%' THEN 'Saude e Higiene'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%BRINQ%' THEN 'Bem-estar'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%ACESS%' THEN 'Bem-estar'
        WHEN TRANSLATE(UPPER("CategoriaProduto"), 'ÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%SERV%' THEN 'Bem-estar'
        ELSE 'Nao Informado'
    END
FROM stg_pedido
WHERE "CategoriaProduto" IS NOT NULL AND "CategoriaProduto" != '';
