-- =====================================================
-- 04-dim_praca_bridge.sql
-- Cria dim_praca e bridge_loja_praca
-- =====================================================

DROP TABLE IF EXISTS dim_praca CASCADE;
CREATE TABLE dim_praca (
    sk_praca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_praca VARCHAR(10),
    nome_praca VARCHAR(60),
    regional VARCHAR(30),
    domicilios_com_pet INT
);

INSERT INTO dim_praca (sk_praca, cod_praca, nome_praca, regional, domicilios_com_pet)
VALUES (-1, '-1', 'Nao Informado', 'Nao Informado', NULL);

INSERT INTO dim_praca (cod_praca, nome_praca, regional, domicilios_com_pet)
SELECT DISTINCT
    TRIM("Cod_Praca"),
    TRIM("Nome_Praca"),
    TRIM("Regional"),
    CAST(REPLACE(TRIM("Domicilios_Com_Pet"), '.', '') AS INTEGER)
FROM stg_loja_praca
WHERE "Cod_Praca" IS NOT NULL AND "Cod_Praca" != '';

DROP TABLE IF EXISTS bridge_loja_praca CASCADE;
CREATE TABLE bridge_loja_praca (
    cod_loja VARCHAR(10),
    sk_praca INT,
    fator_publico DECIMAL(6,4),
    FOREIGN KEY (sk_praca) REFERENCES dim_praca(sk_praca)
);

INSERT INTO bridge_loja_praca (cod_loja, sk_praca, fator_publico)
SELECT DISTINCT
    TRIM(slp."Cod Loja"),
    dp.sk_praca,
    CAST(REPLACE(TRIM(slp."Percentual_Publico"), ',', '.') AS DECIMAL(6,4))
FROM stg_loja_praca slp
JOIN dim_praca dp ON TRIM(slp."Cod_Praca") = dp.cod_praca
WHERE slp."Cod Loja" IS NOT NULL AND slp."Cod Loja" != '';
