-- =====================================================
-- 05-fato_pedido.sql
-- Cria a função de conversão e a fato_pedido
-- =====================================================

-- =====================================================
-- FUNÇÃO PARA CONVERTER VALOR MONETÁRIO
-- =====================================================

CREATE OR REPLACE FUNCTION converter_valor_monetario(valor TEXT)
RETURNS DECIMAL(15,2) AS $$
DECLARE
    valor_limpo TEXT;
    resultado DECIMAL(15,2);
    parte_decimal TEXT;
BEGIN
    IF valor IS NULL OR valor = '' OR valor = '-' THEN
        RETURN NULL;
    END IF;
    
    valor_limpo := TRIM(REPLACE(valor, 'R$', ''));
    valor_limpo := TRIM(REPLACE(valor_limpo, ' ', ''));
    
    IF valor_limpo = '' THEN
        RETURN NULL;
    END IF;
    
    IF valor_limpo LIKE '%.%,%' THEN
        valor_limpo := REPLACE(REPLACE(valor_limpo, '.', ''), ',', '.');
    ELSIF valor_limpo LIKE '%,%' THEN
        valor_limpo := REPLACE(valor_limpo, ',', '.');
    ELSIF valor_limpo LIKE '%.%' THEN
        parte_decimal := SPLIT_PART(valor_limpo, '.', 2);
        IF LENGTH(parte_decimal) <= 2 THEN
            valor_limpo := valor_limpo;
        ELSE
            valor_limpo := REPLACE(valor_limpo, '.', '');
        END IF;
    END IF;
    
    BEGIN
        resultado := valor_limpo::DECIMAL(15,2);
        RETURN resultado;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- CRIA A TABELA FATO_PEDIDO
-- =====================================================

DROP TABLE IF EXISTS fato_pedido CASCADE;
CREATE TABLE fato_pedido (
    sk_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(20),
    sk_tempo_pedido INT,
    sk_tempo_entrega INT,
    sk_loja INT,
    sk_categoria INT,
    houve_desconto VARCHAR(15),
    canal_pedido VARCHAR(20),
    dt_pedido TIMESTAMP,
    qt_itens INT,
    vl_liquido DECIMAL(15,2),
    dias_integracao_separacao INT,
    dias_separacao_nota INT,
    dias_nota_despacho INT,
    dias_despacho_entrega INT,
    dias_total_ate_entrega INT,
    FOREIGN KEY (sk_tempo_pedido) REFERENCES dim_tempo(sk_tempo),
    FOREIGN KEY (sk_tempo_entrega) REFERENCES dim_tempo(sk_tempo),
    FOREIGN KEY (sk_loja) REFERENCES dim_loja(sk_loja),
    FOREIGN KEY (sk_categoria) REFERENCES dim_categoria(sk_categoria)
);

-- =====================================================
-- INSERT DA FATO_PEDIDO
-- =====================================================

WITH dados AS (
    SELECT 
        "NumeroPedido",
        "DtHoraPedido",
        "CategoriaProduto",
        "QTD.Itens",
        "ValorLiquidoPedido(R$)",
        "ValorBruto",
        "HouveDesconto",
        "CanalPedido",
        "Cod Loja",
        "Loja-Nome",
        "DtHoraIntegracaoERP",
        "Dt Separacao Estoque",
        "DtNotaFiscal",
        "Dt_Despacho_Transportador",
        "DtEntregaCliente",
        MAKE_DATE(
            SUBSTRING(SUBSTRING("DtHoraPedido", 1, 10), 7, 4)::INT,
            SUBSTRING(SUBSTRING("DtHoraPedido", 1, 10), 1, 2)::INT,
            SUBSTRING(SUBSTRING("DtHoraPedido", 1, 10), 4, 2)::INT
        ) AS dt_pedido_convertida,
        CASE 
            WHEN "DtHoraIntegracaoERP" IS NOT NULL AND "DtHoraIntegracaoERP" != '' 
            THEN MAKE_DATE(
                SUBSTRING(SUBSTRING("DtHoraIntegracaoERP", 1, 10), 7, 4)::INT,
                SUBSTRING(SUBSTRING("DtHoraIntegracaoERP", 1, 10), 1, 2)::INT,
                SUBSTRING(SUBSTRING("DtHoraIntegracaoERP", 1, 10), 4, 2)::INT
            )
            ELSE NULL 
        END AS dt_integracao,
        CASE 
            WHEN "Dt Separacao Estoque" IS NOT NULL AND "Dt Separacao Estoque" != '' 
            THEN "Dt Separacao Estoque"::date 
            ELSE NULL 
        END AS dt_separacao,
        CASE 
            WHEN "DtNotaFiscal" IS NOT NULL AND "DtNotaFiscal" != '' 
            THEN "DtNotaFiscal"::date 
            ELSE NULL 
        END AS dt_nota,
        CASE 
            WHEN "Dt_Despacho_Transportador" IS NOT NULL AND "Dt_Despacho_Transportador" != '' 
            THEN "Dt_Despacho_Transportador"::date 
            ELSE NULL 
        END AS dt_despacho,
        CASE 
            WHEN "DtEntregaCliente" IS NOT NULL AND "DtEntregaCliente" != '' 
            THEN "DtEntregaCliente"::date 
            ELSE NULL 
        END AS dt_entrega_convertida,
        UPPER(
            unaccent(
                CASE 
                    WHEN UPPER(unaccent(REPLACE(REPLACE("Loja-Nome", '/SC', ''), '  ', ' '))) LIKE '%BLUMENAL%' 
                        THEN 'PATA AMIGA BLUMENAU CENTRO'
                    WHEN UPPER(unaccent(REPLACE(REPLACE("Loja-Nome", '/SC', ''), '  ', ' '))) LIKE '%FLORIPA%' 
                        THEN 'PATA AMIGA FLORIANOPOLIS NORTE'
                    WHEN UPPER(unaccent(REPLACE(REPLACE("Loja-Nome", '/SC', ''), '  ', ' '))) LIKE '%JGUA%' 
                        THEN 'PATA AMIGA JARAGUA DO SUL'
                    ELSE TRIM(REPLACE(REPLACE("Loja-Nome", '/SC', ''), '  ', ' '))
                END
            )
        ) AS chave_loja_padronizada
    FROM stg_pedido
)
INSERT INTO fato_pedido (
    numero_pedido, sk_tempo_pedido, sk_tempo_entrega, sk_loja, sk_categoria,
    houve_desconto, canal_pedido, dt_pedido, qt_itens, vl_liquido,
    dias_integracao_separacao, dias_separacao_nota, dias_nota_despacho,
    dias_despacho_entrega, dias_total_ate_entrega
)
SELECT
    d."NumeroPedido",
    COALESCE(tp.sk_tempo, -1),
    COALESCE(te.sk_tempo, -1),
    COALESCE(dl.sk_loja, -1),
    COALESCE(dc.sk_categoria, -1),
    CASE 
        WHEN UPPER(TRIM(d."HouveDesconto")) IN ('S', 'SIM', '1', 'X', 'TRUE', 'V') THEN 'Sim'
        WHEN UPPER(TRIM(d."HouveDesconto")) IN ('N', 'NAO', '0', 'FALSE', 'F') THEN 'Nao'
        ELSE 'Nao Informado'
    END,
    CASE 
        WHEN UPPER(TRIM(d."CanalPedido")) LIKE '%WHATS%' THEN 'WhatsApp'
        WHEN UPPER(TRIM(d."CanalPedido")) LIKE '%APP%' THEN 'App'
        WHEN UPPER(TRIM(d."CanalPedido")) LIKE '%SITE%' THEN 'Site'
        WHEN UPPER(TRIM(d."CanalPedido")) LIKE '%LOJA%' THEN 'Loja Fisica'
        WHEN UPPER(TRIM(d."CanalPedido")) LIKE '%TEL%' THEN 'Telefone'
        ELSE 'Nao Informado'
    END,
    d.dt_pedido_convertida,
    CASE 
        WHEN d."QTD.Itens" IS NULL OR d."QTD.Itens" = '' OR d."QTD.Itens" = '-' THEN NULL
        ELSE CAST(d."QTD.Itens" AS INTEGER)
    END,
    -- LÓGICA: usa vl_liquido, mas se for 0 ou NULL, usa o valor bruto
    CASE 
        WHEN converter_valor_monetario(d."ValorLiquidoPedido(R$)") IS NOT NULL 
             AND converter_valor_monetario(d."ValorLiquidoPedido(R$)") > 0 
        THEN converter_valor_monetario(d."ValorLiquidoPedido(R$)")
        ELSE converter_valor_monetario(d."ValorBruto")
    END AS vl_liquido,
    CASE 
        WHEN d.dt_separacao IS NOT NULL AND d.dt_integracao IS NOT NULL
        THEN (d.dt_separacao - d.dt_integracao)
        ELSE NULL 
    END,
    CASE 
        WHEN d.dt_nota IS NOT NULL AND d.dt_separacao IS NOT NULL
        THEN (d.dt_nota - d.dt_separacao)
        ELSE NULL 
    END,
    CASE 
        WHEN d.dt_despacho IS NOT NULL AND d.dt_nota IS NOT NULL
        THEN (d.dt_despacho - d.dt_nota)
        ELSE NULL 
    END,
    CASE 
        WHEN d.dt_entrega_convertida IS NOT NULL AND d.dt_despacho IS NOT NULL
        THEN (d.dt_entrega_convertida - d.dt_despacho)
        ELSE NULL 
    END,
    CASE 
        WHEN d.dt_entrega_convertida IS NOT NULL AND d.dt_integracao IS NOT NULL
        THEN (d.dt_entrega_convertida - d.dt_integracao)
        ELSE NULL 
    END
FROM dados d
LEFT JOIN dim_tempo tp ON tp.data_referencia = d.dt_pedido_convertida
LEFT JOIN dim_tempo te ON te.data_referencia = d.dt_entrega_convertida
LEFT JOIN dim_loja dl ON dl.chave_loja = d.chave_loja_padronizada
LEFT JOIN dim_categoria dc ON dc.categoria_origem = d."CategoriaProduto";
